import { THEME } from './defaults.js';

export const dark = {
    ...THEME,
    BACKGROUND: '#000000',
    TEXT_DEFAULT: '#ffffff',
    SVG_BACKGROUND: '#1a1a1a',
    INFO_BACKGROUND: '#1a1a1a',
    REFERENCE_BACKGROUND: '#1a1a1a',
    SHAPE_FILL: '#2a2a2a',
    SHAPE_STROKE: '#444',
    SHAPE_HOVER_FILL: '#3a3a3a',
    TEXT_COLOR: ['#ffffff', '#aaaaaa', '#909090', '#666666'],
    ARROW_COLOR: "#666",
    LINK: '#00cccc',
    BUTTON_FILL: '#2a2a2a',
    BUTTON_BORDER: '#444',
    BUTTON_SYMBOL_COLOR: '#ffffff',
    BUTTON_HOVER_FILL: '#3a3a3a',
    BUTTON_HOVER_SYMBOL_COLOR: '#ffffff',
    DISABLED_BUTTON_FILL: '#1a1a1a',
    DISABLED_BUTTON_BORDER: '#2a2a2a',
    DISABLED_BUTTON_SYMBOL_COLOR: '#3a3a3a',
    SLIDER_BACKGROUND: '#888888',
    SLIDER_BUTTON: '#444444',
    SLIDER_CHECKED: '#00a0a0',
    SCROLLBAR_BACKGROUND: '#d0d0d0',
    SCROLLBAR_BUTTON: '#666',
    SCROLLBAR_HOVER: '#444',
};

export const light = {
    ...THEME,
    BACKGROUND: '#f8f8f8',
    TEXT_DEFAULT: '#333333',
    SVG_BACKGROUND: '#ededed',
    INFO_BACKGROUND: '#ededed',
    REFERENCE_BACKGROUND: '#ededed',
    SHAPE_FILL: '#dcdcdc',
    SHAPE_STROKE: '',
    SHAPE_HOVER_FILL: '#d5d5d5',
    TEXT_COLOR: ['#333333', '#555555', '#777777', '#999999'],
    ARROW_COLOR: "#555555",
    LINK: '#0066cc',
    BUTTON_FILL: '#e2e2e2',
    BUTTON_BORDER: '#c7c7c7',
    BUTTON_SYMBOL_COLOR: '#333333',
    BUTTON_HOVER_FILL: '#d5d5d5',
    BUTTON_HOVER_SYMBOL_COLOR: '#333333',
    DISABLED_BUTTON_FILL: '#ebebeb',
    DISABLED_BUTTON_BORDER: '#dcdcdc',
    DISABLED_BUTTON_SYMBOL_COLOR: '#c2c2c2',
    SLIDER_BACKGROUND: '#dcdcdc',
    SLIDER_BUTTON: '#bfbfbf',
    SLIDER_CHECKED: '#0077aa',
    SCROLLBAR_BACKGROUND: '#ededed',
    SCROLLBAR_BUTTON: '#c7c7c7',
    SCROLLBAR_HOVER: '#b0b0b0',
};
